# Please use sounds from: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# Please use particles from: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
preset-tools:
    inventory:
        lore:
            - 'Send blocks straight to your inventory!'
    smelters:
        lore:
            - 'Automatically smelts blocks!'
        smelts:
            COBBLESTONE: STONE
            IRON_ORE: IRON_INGOT
            GOLD_ORE: GOLD_INGOT
        fortune:
            - 'IRON_INGOT'
            - 'GOLD_INGOT'
    lumber:
        lore:
            - 'Deforest the world!'
        delay: 2
        effective:
            - 'OAK_LOG'
            - 'SPRUCE_LOG'
            - 'BIRCH_LOG'
            - 'JUNGLE_LOG'
            - 'ACACIA_LOG'
            - 'DARK_OAK_LOG'
    explosive:
        lore:
            - 'It goes boom!'
    bountiful:
        lore:
            - 'Harvest more ores!'
            - 'May break value blocks'
        degrade-chance: 40
        trigger:
            - 'STONE'
        value:
            - 'EMERALD_ORE'
            - 'DIAMOND_ORE'
custom-tools:
    special:
        lore:
            - 'this is a special pick'
        sound: ENTITY_PLAYER_LEVELUP
        particle: CRIT_MAGIC
        command-groups:
            1:
                chance: 0.01
                commands:
                    - 'msg %player_name% this is a rare event!'
                    - 'give %player_name% diamond 1'
            2:
                chance: 25
                commands:
                    - 'msg %player_name% this is not a rare event...'
                    - 'give %player_name% stone 1'